defmodule Musubi.Codegen.TypeScript do
  @moduledoc """
  TypeScript codegen for every Musubi `state do` module exposed by the
  current Mix project. Emits a single ambient `.d.ts` bundle.

  ## Output shape

  One file (`priv/codegen/ts/musubi.d.ts` by default) containing:

    * one top-level `declare namespace <Root>` block (root namespace
      configurable via `config :musubi, :ts_codegen_root_namespace,
      "Musubi"`) carrying shared marker types (`StoreId`, `AsyncResult`,
      `StoreDef`, `StoreField`, `StreamField`, `AsyncField`) and an
      `interface Stores` populated with one entry per Musubi.Store
      module
    * one top-level `declare namespace <Path>` block per Musubi.State
      module, nested to mirror the Elixir module tree, each holding an
      `interface <Name> { ... }` declaration

  The file is an ambient `.d.ts` (no top-level `import` / `export`), so
  tsc picks it up automatically when the file falls under the project's
  `include` glob. Consumers reference generated types as e.g.
  `Musubi.Stores`, `MyApp.States.LineItemState`, without any side-effect
  import.

  Consumers thread the generated `Musubi.Stores` type into the
  `createMusubi<R>()` factory (from `@musubi/react`) or `connect<R>()`
  (from `@musubi/client`) exactly once; every returned hook / API closes
  over `R` so subsequent calls infer the store type from the `module`
  string literal alone.

  ## Type mapping

  | Musubi field type AST            | TypeScript                              |
  | :------------------------------ | :-------------------------------------- |
  | `String.t()` / `binary()`       | `string`                                |
  | `integer()` / `float()`         | `number`                                |
  | `boolean()`                     | `boolean`                               |
  | `atom()`                        | `string` (atoms serialize as strings)   |
  | `:literal` (atom literal)       | `"literal"`                             |
  | `nil`                           | `null`                                  |
  | `map()`                         | `Record<string, unknown>`               |
  | `%{key: T}`                     | `{ key: T }` (literal-keyed map)        |
  | `list(T)` / `[T]`               | `T[]`                                   |
  | `stream(T)`                     | `<Root>.StreamField<T>`                 |
  | `T \\| U`                       | `T \| U`                                |
  | `Module.t()`                    | full Elixir alias path                  |
  | `Module.state()`                | `<Root>.StoreField<"Full.Module">`      |
  | `Musubi.AsyncResult.of(T)`       | `<Root>.AsyncField<T>`                  |
  """

  alias Musubi.Codegen.Manifest
  alias Musubi.Codegen.TypeScript.TypeRenderer

  @default_root "Musubi"

  @typedoc """
  An entry produced by `Musubi.Codegen.Manifest.list/0` and consumed by
  `render/1`. Pre-loaded reflection data — `render/1` performs no
  module-callback lookups itself.
  """
  @type entry() :: Manifest.entry()

  @doc """
  Renders one TypeScript bundle covering every `{module, data}` entry in
  `entries`. Returns the rendered source string. Raises `ArgumentError` on
  a duplicate fully-qualified module name (defensive — real modules can't
  collide).

  Options:
    * `:root_namespace` — root namespace name. Defaults to
      `Application.get_env(:musubi, :ts_codegen_root_namespace, "Musubi")`.
  """
  @spec render([entry()]) :: String.t()
  @spec render([entry()], keyword()) :: String.t()
  def render(entries, opts \\ []) when is_list(entries) do
    root = Keyword.get(opts, :root_namespace, configured_root_namespace())

    entries =
      entries
      |> Enum.uniq_by(fn {module, _data} -> module end)
      |> Enum.sort_by(fn {module, _data} -> Module.split(module) end)
      |> validate_no_duplicates!()
      |> normalize_kinds()

    {store_entries, state_entries} =
      Enum.split_with(entries, fn {_module, %{kind: kind}} -> kind == :store end)

    iodata = [
      header(),
      root_namespace_block(root, store_entries),
      state_namespaces_block(state_entries, root)
    ]

    IO.iodata_to_binary(iodata)
  end

  @doc """
  Returns the configured root namespace, falling back to `"Musubi"`.
  """
  @spec configured_root_namespace() :: String.t()
  def configured_root_namespace do
    Application.get_env(:musubi, :ts_codegen_root_namespace, @default_root)
  end

  defp header do
    "// Generated by `mix compile.musubi_ts`. Do not edit by hand.\n\n"
  end

  defp validate_no_duplicates!(entries) do
    duplicates =
      entries
      |> Enum.frequencies_by(fn {module, _data} -> Module.split(module) end)
      |> Enum.filter(fn {_path, count} -> count > 1 end)

    case duplicates do
      [] -> entries
      _list -> raise ArgumentError, "duplicate Musubi module paths: #{inspect(duplicates)}"
    end
  end

  defp normalize_kinds(entries) do
    Enum.map(entries, fn {module, data} ->
      kind = Map.get(data, :kind) || :state
      {module, Map.put(data, :kind, kind)}
    end)
  end

  # ---------------------------------------------------------------------------
  # Root namespace
  # ---------------------------------------------------------------------------

  defp root_namespace_block(root, store_entries) do
    [
      "declare namespace ",
      root,
      " {\n",
      shared_marker_types(),
      "\n",
      stores_interface_block(store_entries, root),
      "}\n"
    ]
  end

  defp shared_marker_types do
    """
      type StoreId = string[]

      type AsyncError =
        | { kind: "error"; value: unknown }
        | { kind: "exit"; value: unknown }

      type AsyncResult<T> =
        | { __musubi_async__: true; status: "loading"; result: T | null; reason: null }
        | { __musubi_async__: true; status: "ok"; result: T; reason: null }
        | { __musubi_async__: true; status: "failed"; result: T | null; reason: AsyncError | unknown }

      const Type: unique symbol

      interface StoreDef<Module extends string, Shape, Commands, Events = {}> {
        readonly [Type]: {
          module: Module
          shape: Shape
          commands: Commands
          events: Events
        }
      }

      type StoreField<Module extends string> = {
        readonly [Type]: { kind: "store"; module: Module }
      }

      type StreamField<Item> = {
        readonly [Type]: { kind: "stream"; item: Item }
      }

      type AsyncField<Value> = {
        readonly [Type]: { kind: "async"; value: Value }
      }

      type UploadConfig = {
        readonly accept: readonly string[] | "any"
        readonly maxEntries: number
        readonly maxFileSize: number
        readonly chunkSize: number
      }

      type UploadEntryStatus =
        | "pending"
        | "uploading"
        | "success"
        | "error"
        | "cancelled"

      type UploadStatus =
        | "idle"
        | "selecting"
        | "uploading"
        | "success"
        | "error"
        | "cancelled"

      type UploadError = { readonly code: string; readonly message: string }

      type UploadEntry = {
        readonly ref: string
        readonly clientName: string
        readonly clientSize: number
        readonly clientType: string
        readonly progress: number
        readonly status: UploadEntryStatus
        readonly errors: readonly UploadError[]
      }

      type UploadHandle = {
        readonly config: UploadConfig
        readonly status: UploadStatus
        readonly entries: readonly UploadEntry[]
        readonly errors: readonly UploadError[]
        readonly progress: number
        readonly isIdle: boolean
        readonly isSelecting: boolean
        readonly isUploading: boolean
        readonly isSuccess: boolean
        readonly isError: boolean
        select(files: FileList | File[]): Promise<readonly UploadEntry[]>
        start(): Promise<void>
        cancel(entryRef?: string): Promise<void>
        reset(): Promise<void>
      }

      type UploadField = {
        readonly [Type]: { kind: "upload" }
      }
    """
  end

  defp stores_interface_block([], _root) do
    "  interface Stores {}\n"
  end

  defp stores_interface_block(store_entries, root) do
    body = Enum.map_join(store_entries, "\n\n", &render_store_def(&1, "    ", root))

    [
      "  interface Stores {\n",
      body,
      "\n",
      "  }\n"
    ]
  end

  defp render_store_def({module, data}, indent, root) do
    fields = Map.fetch!(data, :fields)
    commands = Map.fetch!(data, :commands)
    events = Map.get(data, :events, [])
    uploads = Map.get(data, :uploads, [])

    ensure_no_state_upload_collision!(module, fields, uploads)

    module_name = full_module_name(module)
    shape_indent = indent <> "  "
    field_lines = render_state_fields(fields, shape_indent <> "  ", root)
    upload_lines = render_upload_fields(uploads, shape_indent <> "  ")

    body = Enum.join(field_lines ++ upload_lines, "\n")

    [
      indent,
      inspect(module_name),
      ": StoreDef<\n",
      shape_indent,
      inspect(module_name),
      ",\n",
      shape_indent,
      "{\n",
      body,
      "\n",
      shape_indent,
      "},\n",
      render_commands_block(commands, shape_indent, root),
      ",\n",
      render_events_block(events, shape_indent, root),
      "\n",
      indent,
      ">"
    ]
  end

  defp render_events_block([], indent, _root), do: [indent, "{}"]

  defp render_events_block(events, indent, root) do
    inner_indent = indent <> "  "

    body =
      Enum.map_join(events, "\n", fn %{name: name, payload_fields: payload_fields} ->
        entry_indent = inner_indent <> "  "

        IO.iodata_to_binary([
          inner_indent,
          Atom.to_string(name),
          ": {\n",
          render_command_fields_block("payload", payload_fields, entry_indent, root),
          "\n",
          inner_indent,
          "}"
        ])
      end)

    [indent, "{\n", body, "\n", indent, "}"]
  end

  defp render_upload_fields([], _indent), do: []

  defp render_upload_fields(uploads, indent) do
    Enum.map(uploads, fn upload ->
      name = upload_name(upload)
      "#{indent}#{name}: UploadField"
    end)
  end

  defp upload_name(%{name: name}) when is_atom(name), do: Atom.to_string(name)
  defp upload_name(%{name: name}) when is_binary(name), do: name

  defp ensure_no_state_upload_collision!(module, fields, uploads) do
    field_names = MapSet.new(fields, & &1.name)

    case Enum.find(uploads, fn upload -> MapSet.member?(field_names, upload.name) end) do
      nil ->
        :ok

      %{name: name} ->
        raise ArgumentError,
              "Musubi TypeScript codegen: upload :#{name} on #{inspect(module)} " <>
                "collides with a state field of the same name; rename one before " <>
                "the generator can emit a merged shape"
    end
  end

  defp render_commands_block([], indent, _root), do: [indent, "{}"]

  defp render_commands_block(commands, indent, root) do
    inner_indent = indent <> "  "

    body =
      Enum.map_join(commands, "\n", fn command ->
        render_command_entry(command, inner_indent, root)
      end)

    [indent, "{\n", body, "\n", indent, "}"]
  end

  defp render_command_entry(
         %{name: name, payload_fields: payload_fields} = command,
         indent,
         root
       ) do
    inner_indent = indent <> "  "
    reply_fields = Map.get(command, :reply_fields, [])

    [
      indent,
      Atom.to_string(name),
      ": {\n",
      render_command_fields_block("payload", payload_fields, inner_indent, root),
      "\n",
      render_command_fields_block("reply", reply_fields, inner_indent, root),
      "\n",
      indent,
      "}"
    ]
  end

  defp render_command_fields_block(label, [], indent, _root) do
    [indent, label, ": ", empty_value(label)]
  end

  defp render_command_fields_block(label, fields, indent, root) do
    inner_indent = indent <> "  "
    field_lines = render_command_field_lines(fields, inner_indent, root)

    [
      indent,
      label,
      ": {\n",
      Enum.join(field_lines, "\n"),
      "\n",
      indent,
      "}"
    ]
  end

  defp empty_value("reply"), do: "never"
  defp empty_value(_label), do: "{}"

  defp render_command_field_lines(fields, indent, root) do
    Enum.map(fields, fn %{name: name, type: type_ast} = field ->
      type = TypeRenderer.render(type_ast, root_namespace: root)
      base = "#{indent}#{name}: #{type}"

      case doc_opt(field) do
        nil -> base
        doc -> "#{indent}/** #{doc} */\n" <> base
      end
    end)
  end

  defp doc_opt(%{opts: opts}) when is_list(opts), do: Keyword.get(opts, :doc)
  defp doc_opt(_field), do: nil

  # ---------------------------------------------------------------------------
  # State namespaces
  # ---------------------------------------------------------------------------

  defp state_namespaces_block([], _root), do: []

  defp state_namespaces_block(state_entries, root) do
    tree = build_state_tree(state_entries)
    body = emit_state_tree(tree, 0, root)

    ["\n", body]
  end

  defp build_state_tree(entries) do
    Enum.reduce(entries, %{}, fn {module, _data} = entry, acc ->
      insert_state_entry(acc, Module.split(module), entry)
    end)
  end

  defp insert_state_entry(tree, [last], entry) do
    Map.update(tree, last, {%{}, entry}, fn {children, _existing} -> {children, entry} end)
  end

  defp insert_state_entry(tree, [head | rest], entry) do
    Map.update(tree, head, {insert_state_entry(%{}, rest, entry), nil}, fn {children, leaf} ->
      {insert_state_entry(children, rest, entry), leaf}
    end)
  end

  defp emit_state_tree(tree, depth, root) do
    tree
    |> Enum.sort_by(fn {segment, _entry} -> segment end)
    |> Enum.map(&emit_state_node(&1, depth, root))
    |> Enum.intersperse("\n")
  end

  defp emit_state_node({segment, {children, nil}}, depth, root) do
    indent = String.duplicate("  ", depth)
    children_body = emit_state_tree(children, depth + 1, root)

    emit_namespace_block(segment, children_body, indent, namespace_keyword(depth))
  end

  # Top-level leaf with no children: wrap in `declare namespace` so the
  # ambient .d.ts file picks it up. Nested leaves stay as bare
  # `interface` declarations inside their parent namespace.
  defp emit_state_node({segment, {children, leaf_entry}}, 0, root)
       when map_size(children) == 0 do
    emit_namespace_block(
      segment,
      render_state_interface(segment, fields_from(leaf_entry), "  ", root),
      "",
      namespace_keyword(0)
    )
  end

  defp emit_state_node({segment, {children, leaf_entry}}, depth, root)
       when map_size(children) == 0 do
    indent = String.duplicate("  ", depth)
    render_state_interface(segment, fields_from(leaf_entry), indent, root)
  end

  defp emit_state_node({segment, {children, leaf_entry}}, depth, root) do
    indent = String.duplicate("  ", depth)
    children_body = emit_state_tree(children, depth + 1, root)

    leaf_interface =
      render_state_interface(segment, fields_from(leaf_entry), indent <> "  ", root)

    emit_namespace_block(
      segment,
      [leaf_interface, children_body],
      indent,
      namespace_keyword(depth)
    )
  end

  defp emit_namespace_block(segment, body, indent, keyword) do
    [indent, keyword, segment, " {\n", body, indent, "}\n"]
  end

  defp namespace_keyword(0), do: "declare namespace "
  defp namespace_keyword(_depth), do: "namespace "

  defp fields_from({_module, %{fields: fields}}), do: fields

  defp render_state_interface(name, fields, indent, root) do
    field_lines = render_state_fields(fields, indent <> "  ", root)

    [
      indent,
      "interface ",
      name,
      " {\n",
      Enum.join(field_lines, "\n"),
      "\n",
      indent,
      "}\n"
    ]
  end

  # ---------------------------------------------------------------------------
  # Shared field rendering
  # ---------------------------------------------------------------------------

  defp render_state_fields(fields, indent, root) do
    fields
    |> Manifest.renderable_fields()
    |> Enum.map(fn %{name: field_name, type: type_ast} ->
      "#{indent}#{field_name}: #{TypeRenderer.render(type_ast, root_namespace: root)}"
    end)
  end

  defp full_module_name(module) when is_atom(module) do
    module |> Module.split() |> Enum.join(".")
  end
end
