// Generated by `mix compile.musubi_rust`. Do not edit by hand.
// Include as a module file (`mod generated;`) or via `include!`.

#![allow(clippy::all, dead_code, unused_imports)]

// Prelude: re-exports only. The shared runtime types are owned by the
// client crate (`:rust_codegen_runtime_path`, default `musubi_client`).
pub mod musubi {
    pub use ::musubi_client::generated::{
        AsyncError, AsyncResult, Command, Event, NoReply, Store, StoreField, StoreId, UploadSlot,
    };
}

pub mod chat_room {
    #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
    pub struct AttachmentState {
        pub name: String,
        pub content_type: String,
        pub size: i64,
        pub url: String,
    }

    #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
    pub struct MessageState {
        pub id: String,
        pub body: String,
        pub sender: String,
        pub attachment: Option<super::chat_room::AttachmentState>,
    }

    #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
    pub struct OnlineUser {
        pub id: String,
        pub name: String,
    }

    pub mod stores {
        pub mod chat_room_store {
            /// Zero-sized marker type implementing `Store`. Distinct from `State`.
            pub struct ChatRoomStore;

            impl super::super::super::musubi::Store for ChatRoomStore {
                const MODULE: &'static str = "ChatRoom.Stores.ChatRoomStore";
                type State = State;
                type Params = Params;
            }

            /// The store's rendered shape: state fields plus one `UploadSlot` per
            /// declared upload. Reached as `<ChatRoomStore as Store>::State`.
            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct State {
                pub messages: super::super::super::musubi::AsyncResult<
                    Vec<super::super::super::chat_room::MessageState>,
                >,
                pub current_user: super::super::super::chat_room::OnlineUser,
                pub online_users: super::super::super::musubi::AsyncResult<
                    Vec<super::super::super::chat_room::OnlineUser>,
                >,
                pub last_send_status: ChatRoomStoreLastSendStatus,
                pub attachment: super::super::super::musubi::UploadSlot,
            }

            /// The mount params object, one field per `attr/3` declaration: required
            /// attrs are plain fields, optional ones `Option` that serialize to an
            /// absent key rather than an explicit `null`. A store declaring no `attr`
            /// gets an empty struct, which serializes to `{}`.
            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct Params {
                pub room_id: String,
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            #[serde(tag = "type")]
            pub enum ChatRoomStoreLastSendStatus {
                #[serde(rename = "idle")]
                Idle,
                #[serde(rename = "ok")]
                Ok { id: String },
                #[serde(rename = "failed")]
                Failed { reason: String },
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SetName {
                pub name: String,
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SetNameReply {
                pub ok: bool,
                pub name: String,
            }

            impl super::super::super::musubi::Command<ChatRoomStore> for SetName {
                const NAME: &'static str = "set_name";
                type Reply = SetNameReply;
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SendMessage {
                pub body: String,
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SendMessageReply {
                pub queued: bool,
            }

            impl super::super::super::musubi::Command<ChatRoomStore> for SendMessage {
                const NAME: &'static str = "send_message";
                type Reply = SendMessageReply;
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct Attach {}

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct AttachReply {
                pub attached: bool,
                pub name: Option<String>,
            }

            impl super::super::super::musubi::Command<ChatRoomStore> for Attach {
                const NAME: &'static str = "attach";
                type Reply = AttachReply;
            }
        }
    }
}
