// Generated by `mix compile.musubi_rust`. Do not edit by hand.
// Include as a module file (`mod generated;`) or via `include!`.

#![allow(clippy::all, dead_code, unused_imports)]

// Prelude: re-exports only. The shared runtime types are owned by the
// client crate (`:rust_codegen_runtime_path`, default `musubi_client`).
pub mod musubi {
    pub use ::musubi_client::generated::{
        AsyncError, AsyncResult, AsyncState, Command, Event, NoReply, State, StateTree, Store,
        StoreField, StoreId, StoreState, StreamState, Subscription, UploadSlot, UploadSlotState,
    };
}

pub mod chat_room {
    #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
    pub struct AttachmentState {
        pub name: String,
        pub content_type: String,
        pub size: i64,
        pub url: String,
    }

    /// Typed navigation for the shape above: one accessor per declared field,
    /// each handing back a handle rather than a value
    /// (`docs/rust-reactive-state.md` §4.2). Reach it through `nav`.
    pub trait AttachmentStateExt {
        fn name(&self) -> super::musubi::State<String>;
        fn content_type(&self) -> super::musubi::State<String>;
        fn size(&self) -> super::musubi::State<i64>;
        fn url(&self) -> super::musubi::State<String>;
    }

    impl AttachmentStateExt for super::musubi::State<AttachmentState> {
        fn name(&self) -> super::musubi::State<String> {
            self.child("name")
        }
        fn content_type(&self) -> super::musubi::State<String> {
            self.child("content_type")
        }
        fn size(&self) -> super::musubi::State<i64> {
            self.child("size")
        }
        fn url(&self) -> super::musubi::State<String> {
            self.child("url")
        }
    }

    #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
    pub struct MessageState {
        pub id: String,
        pub body: String,
        pub sender: String,
        pub attachment: Option<super::chat_room::AttachmentState>,
    }

    /// Typed navigation for the shape above: one accessor per declared field,
    /// each handing back a handle rather than a value
    /// (`docs/rust-reactive-state.md` §4.2). Reach it through `nav`.
    pub trait MessageStateExt {
        fn id(&self) -> super::musubi::State<String>;
        fn body(&self) -> super::musubi::State<String>;
        fn sender(&self) -> super::musubi::State<String>;
        fn attachment(&self) -> super::musubi::State<Option<super::chat_room::AttachmentState>>;
    }

    impl MessageStateExt for super::musubi::State<MessageState> {
        fn id(&self) -> super::musubi::State<String> {
            self.child("id")
        }
        fn body(&self) -> super::musubi::State<String> {
            self.child("body")
        }
        fn sender(&self) -> super::musubi::State<String> {
            self.child("sender")
        }
        fn attachment(&self) -> super::musubi::State<Option<super::chat_room::AttachmentState>> {
            self.child("attachment")
        }
    }

    #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
    pub struct OnlineUser {
        pub id: String,
        pub name: String,
    }

    /// Typed navigation for the shape above: one accessor per declared field,
    /// each handing back a handle rather than a value
    /// (`docs/rust-reactive-state.md` §4.2). Reach it through `nav`.
    pub trait OnlineUserExt {
        fn id(&self) -> super::musubi::State<String>;
        fn name(&self) -> super::musubi::State<String>;
    }

    impl OnlineUserExt for super::musubi::State<OnlineUser> {
        fn id(&self) -> super::musubi::State<String> {
            self.child("id")
        }
        fn name(&self) -> super::musubi::State<String> {
            self.child("name")
        }
    }

    pub mod stores {
        pub mod chat_room_store {
            /// Zero-sized marker type implementing `Store`. Distinct from `State`.
            pub struct ChatRoomStore;

            impl super::super::super::musubi::Store for ChatRoomStore {
                const MODULE: &'static str = "ChatRoom.Stores.ChatRoomStore";
                type State = State;
                type Params = Params;
            }

            /// The store's rendered shape: state fields plus one `UploadSlot` per
            /// declared upload. Reached as `<ChatRoomStore as Store>::State`.
            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct State {
                pub messages: super::super::super::musubi::AsyncResult<
                    Vec<super::super::super::chat_room::MessageState>,
                >,
                pub current_user: super::super::super::chat_room::OnlineUser,
                pub online_users: super::super::super::musubi::AsyncResult<
                    Vec<super::super::super::chat_room::OnlineUser>,
                >,
                pub last_send_status: ChatRoomStoreLastSendStatus,
                pub attachment: super::super::super::musubi::UploadSlot,
            }

            /// Typed navigation for the shape above: one accessor per declared field,
            /// each handing back a handle rather than a value
            /// (`docs/rust-reactive-state.md` §4.2). Reach it through `nav`.
            pub trait ChatRoomStoreExt {
                fn messages(
                    &self,
                ) -> super::super::super::musubi::AsyncState<
                    Vec<super::super::super::chat_room::MessageState>,
                >;
                fn current_user(
                    &self,
                ) -> super::super::super::musubi::State<super::super::super::chat_room::OnlineUser>;
                fn online_users(
                    &self,
                ) -> super::super::super::musubi::AsyncState<
                    Vec<super::super::super::chat_room::OnlineUser>,
                >;
                fn last_send_status(
                    &self,
                ) -> super::super::super::musubi::State<ChatRoomStoreLastSendStatus>;
                fn attachment(&self) -> super::super::super::musubi::UploadSlotState;
            }

            impl ChatRoomStoreExt for super::super::super::musubi::State<State> {
                fn messages(
                    &self,
                ) -> super::super::super::musubi::AsyncState<
                    Vec<super::super::super::chat_room::MessageState>,
                > {
                    self.child("messages").into()
                }
                fn current_user(
                    &self,
                ) -> super::super::super::musubi::State<super::super::super::chat_room::OnlineUser>
                {
                    self.child("current_user")
                }
                fn online_users(
                    &self,
                ) -> super::super::super::musubi::AsyncState<
                    Vec<super::super::super::chat_room::OnlineUser>,
                > {
                    self.child("online_users").into()
                }
                fn last_send_status(
                    &self,
                ) -> super::super::super::musubi::State<ChatRoomStoreLastSendStatus>
                {
                    self.child("last_send_status")
                }
                fn attachment(&self) -> super::super::super::musubi::UploadSlotState {
                    self.child("attachment").into()
                }
            }

            impl ChatRoomStoreExt for super::super::super::musubi::StoreState<State> {
                fn messages(
                    &self,
                ) -> super::super::super::musubi::AsyncState<
                    Vec<super::super::super::chat_room::MessageState>,
                > {
                    ChatRoomStoreExt::messages(&self.fields())
                }
                fn current_user(
                    &self,
                ) -> super::super::super::musubi::State<super::super::super::chat_room::OnlineUser>
                {
                    ChatRoomStoreExt::current_user(&self.fields())
                }
                fn online_users(
                    &self,
                ) -> super::super::super::musubi::AsyncState<
                    Vec<super::super::super::chat_room::OnlineUser>,
                > {
                    ChatRoomStoreExt::online_users(&self.fields())
                }
                fn last_send_status(
                    &self,
                ) -> super::super::super::musubi::State<ChatRoomStoreLastSendStatus>
                {
                    ChatRoomStoreExt::last_send_status(&self.fields())
                }
                fn attachment(&self) -> super::super::super::musubi::UploadSlotState {
                    ChatRoomStoreExt::attachment(&self.fields())
                }
            }

            /// The mount params object, one field per `attr/3` declaration: required
            /// attrs are plain fields, optional ones `Option` that serialize to an
            /// absent key rather than an explicit `null`. A store declaring no `attr`
            /// gets an empty struct, which serializes to `{}`.
            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct Params {
                pub room_id: String,
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            #[serde(tag = "type")]
            pub enum ChatRoomStoreLastSendStatus {
                #[serde(rename = "idle")]
                Idle,
                #[serde(rename = "ok")]
                Ok { id: String },
                #[serde(rename = "failed")]
                Failed { reason: String },
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SetName {
                pub name: String,
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SetNameReply {
                pub ok: bool,
                pub name: String,
            }

            impl super::super::super::musubi::Command<ChatRoomStore> for SetName {
                const NAME: &'static str = "set_name";
                type Reply = SetNameReply;
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SendMessage {
                pub body: String,
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct SendMessageReply {
                pub queued: bool,
            }

            impl super::super::super::musubi::Command<ChatRoomStore> for SendMessage {
                const NAME: &'static str = "send_message";
                type Reply = SendMessageReply;
            }

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct Attach {}

            #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
            pub struct AttachReply {
                pub attached: bool,
                pub name: Option<String>,
            }

            impl super::super::super::musubi::Command<ChatRoomStore> for Attach {
                const NAME: &'static str = "attach";
                type Reply = AttachReply;
            }
        }
    }
}

// Navigation traits, flat. One `use <bundle>::nav::*;` per consumer file
// brings every generated accessor into scope.
pub mod nav {
    pub use super::chat_room::AttachmentStateExt;
    pub use super::chat_room::MessageStateExt;
    pub use super::chat_room::OnlineUserExt;
    pub use super::chat_room::stores::chat_room_store::ChatRoomStoreExt;
}
