defmodule Mix.Tasks.Compile.MusubiRustTest do
  # async: false because the test scopes a manifest target_dir override via
  # Process dict and writes the rendered bundle to the configured
  # `:rust_codegen_output_path` (which `config/test.exs` points at
  # `test/tmp/musubi_rust_bundle.rs`). Concurrent runs would race on that path.
  #
  # The `:noop`/drift/`manifests`/`clean` plumbing is shared with
  # `mix compile.musubi_ts` (`Musubi.Codegen.Compiler`) and is covered by
  # `Mix.Tasks.Compile.MusubiTsTest`; only the Rust-specific wiring lives here.
  use ExUnit.Case, async: false

  alias Mix.Tasks.Compile.MusubiRust
  alias Musubi.Codegen.Manifest
  alias Musubi.TestSupport.TypespecProbe
  alias Musubi.TestSupport.TypespecProbeChild

  setup do
    target =
      Path.join(
        System.tmp_dir!(),
        "musubi_rust_compile_#{:erlang.unique_integer([:positive])}"
      )

    File.mkdir_p!(target)
    Process.put(:__musubi_codegen_target_dir__, target)

    output_path = Application.fetch_env!(:musubi, :rust_codegen_output_path)
    File.mkdir_p!(Path.dirname(output_path))
    File.rm(output_path)

    on_exit(fn ->
      File.rm_rf!(target)
      File.rm(output_path)
    end)

    Manifest.stamp(TypespecProbe, "lib/x.ex", target)
    Manifest.stamp(TypespecProbeChild, "lib/y.ex", target)

    {:ok, target: target, output_path: output_path}
  end

  test "writes a fresh bundle covering every stamped module", %{output_path: output_path} do
    assert {:ok, []} = MusubiRust.run([])

    contents = File.read!(output_path)

    assert contents =~ "// Generated by `mix compile.musubi_rust`. Do not edit by hand."
    assert contents =~ "#![allow(clippy::all, dead_code, unused_imports)]"
    assert contents =~ "pub use ::musubi_client::generated::{"
    assert contents =~ "pub mod typespec_probe {"
    assert contents =~ "pub struct TypespecProbe;"
    assert contents =~ ~s|const MODULE: &'static str = "Musubi.TestSupport.TypespecProbe";|
    assert contents =~ ~s|const MODULE: &'static str = "Musubi.TestSupport.TypespecProbeChild";|
    refute contents =~ "crate::"
  end

  test "--check reports drift under the rust compiler name", %{output_path: output_path} do
    File.write!(output_path, "// stale\n")

    assert {:error,
            [
              %Mix.Task.Compiler.Diagnostic{
                severity: :error,
                compiler_name: "musubi_rust",
                file: ^output_path
              }
            ]} = MusubiRust.run(["--check"])

    assert File.read!(output_path) == "// stale\n"
  end
end
