defmodule Musubi.Codegen.RustTest do
  use ExUnit.Case, async: true

  alias Musubi.Codegen.Manifest
  alias Musubi.Codegen.Rust
  alias Musubi.TestSupport.TypespecProbe
  alias Musubi.TestSupport.TypespecProbeChild
  alias Musubi.TestSupport.TypespecProbeNestedState
  alias Musubi.TestSupport.TypespecProbeWithAttrs
  alias Musubi.TestSupport.TypespecProbeWithCommand
  alias Musubi.TestSupport.TypespecProbeWithEvents
  alias Musubi.TestSupport.TypespecProbeWithReply
  alias Musubi.TestSupport.TypespecProbeWithUpload

  doctest Musubi.Codegen.Rust

  # The re-export list is normative: `docs/rust-codegen.md` §4.5 plus the seven
  # state-tree names `docs/rust-reactive-state.md` §4.1 adds. It is filled to
  # rustfmt's `max_width` at the one indent level the prelude item always lands
  # on, so the bundle survives `cargo fmt --check`.
  @preamble """
  // Generated by `mix compile.musubi_rust`. Do not edit by hand.
  // Include as a module file (`mod generated;`) or via `include!`.

  #![allow(clippy::all, dead_code, unused_imports)]

  // Prelude: re-exports only. The shared runtime types are owned by the
  // client crate (`:rust_codegen_runtime_path`, default `musubi_client`).
  pub mod musubi {
      pub use ::musubi_client::generated::{
          AsyncError, AsyncResult, AsyncState, Command, Event, NoReply, State, StateTree, Store,
          StoreField, StoreId, StoreState, StreamState, Subscription, UploadSlot, UploadSlotState,
      };
  }
  """

  # The probe fixtures live under `Musubi.*`, whose top-level `pub mod musubi`
  # carries the same Rust name as the prelude module. The re-export is then the
  # first item of *that* module rather than a sibling `pub mod musubi`, which
  # would be `error[E0428]`.
  @merged_preamble """
  // Generated by `mix compile.musubi_rust`. Do not edit by hand.
  // Include as a module file (`mod generated;`) or via `include!`.

  #![allow(clippy::all, dead_code, unused_imports)]

  pub mod musubi {
      // Prelude: re-exports only. The shared runtime types are owned by the
      // client crate (`:rust_codegen_runtime_path`, default `musubi_client`).
      pub use ::musubi_client::generated::{
          AsyncError, AsyncResult, AsyncState, Command, Event, NoReply, State, StateTree, Store,
          StoreField, StoreId, StoreState, StreamState, Subscription, UploadSlot, UploadSlotState,
      };
  """

  # Emitted above every generated navigation trait; spelled out once so the
  # golden bodies below stay about the accessors.
  @ext_doc """
  /// Typed navigation for the shape above: one accessor per declared field,
  /// each handing back a handle rather than a value
  /// (`docs/rust-reactive-state.md` §4.2). Reach it through `nav`.
  """

  describe "render/1 — empty" do
    test "renders the header and the re-export prelude only" do
      assert Rust.render([]) == @preamble
    end
  end

  describe "render/1 — Musubi.State entry" do
    test "emits a bare struct in the parent module with its hoisted types sorted by name" do
      expected = """
      pub mod test_support {
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct TypespecProbeNestedState {
      pub r#type: TypespecProbeNestedStateType,
      pub shipping: TypespecProbeNestedStateShipping,
      }

      #{@ext_doc}pub trait TypespecProbeNestedStateExt {
      fn r#type(&self) -> super::super::musubi::State<TypespecProbeNestedStateType>;
      fn shipping(&self) -> super::super::musubi::State<TypespecProbeNestedStateShipping>;
      }

      impl TypespecProbeNestedStateExt for super::super::musubi::State<TypespecProbeNestedState> {
      fn r#type(&self) -> super::super::musubi::State<TypespecProbeNestedStateType> {
      self.child("type")
      }
      fn shipping(&self) -> super::super::musubi::State<TypespecProbeNestedStateShipping> {
      self.child("shipping")
      }
      }

      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct TypespecProbeNestedStateShipping {
      pub street: String,
      pub city: String,
      }

      #{@ext_doc}pub trait TypespecProbeNestedStateShippingExt {
      fn street(&self) -> super::super::musubi::State<String>;
      fn city(&self) -> super::super::musubi::State<String>;
      }

      impl TypespecProbeNestedStateShippingExt
      for super::super::musubi::State<TypespecProbeNestedStateShipping>
      {
      fn street(&self) -> super::super::musubi::State<String> {
      self.child("street")
      }
      fn city(&self) -> super::super::musubi::State<String> {
      self.child("city")
      }
      }

      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub enum TypespecProbeNestedStateType {
      #[serde(rename = "guest")]
      Guest,
      #[serde(rename = "member")]
      Member,
      }
      }
      }

      // Navigation traits, flat. One `use <bundle>::nav::*;` per consumer file
      // brings every generated accessor into scope.
      pub mod nav {
      pub use super::musubi::test_support::TypespecProbeNestedStateExt;
      pub use super::musubi::test_support::TypespecProbeNestedStateShippingExt;
      }
      """

      rendered = Rust.render([entry(TypespecProbeNestedState)])

      assert normalize(rendered) == normalize(@merged_preamble <> "\n" <> expected)
    end
  end

  describe "render/1 — nested state modules" do
    test "a leaf with children emits both the struct and a same-named module" do
      entries = [
        {MyApp.States.Cart, state_entry(:title, quote(do: String.t()))},
        {MyApp.States.Cart.Item, state_entry(:sku, quote(do: String.t()))}
      ]

      expected = """
      pub mod my_app {
      pub mod states {
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct Cart {
      pub title: String,
      }

      #{@ext_doc}pub trait CartExt {
      fn title(&self) -> super::super::musubi::State<String>;
      }

      impl CartExt for super::super::musubi::State<Cart> {
      fn title(&self) -> super::super::musubi::State<String> {
      self.child("title")
      }
      }

      pub mod cart {
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct Item {
      pub sku: String,
      }

      #{@ext_doc}pub trait ItemExt {
      fn sku(&self) -> super::super::super::musubi::State<String>;
      }

      impl ItemExt for super::super::super::musubi::State<Item> {
      fn sku(&self) -> super::super::super::musubi::State<String> {
      self.child("sku")
      }
      }
      }
      }
      }

      // Navigation traits, flat. One `use <bundle>::nav::*;` per consumer file
      // brings every generated accessor into scope.
      pub mod nav {
      pub use super::my_app::states::CartExt;
      pub use super::my_app::states::cart::ItemExt;
      }
      """

      assert normalize(Rust.render(entries)) == normalize(@preamble <> "\n" <> expected)
    end
  end

  describe "render/1 — Musubi.Store entry" do
    test "a store is a module of its own carrying the marker, the impl and State" do
      expected = """
      pub mod test_support {
      pub mod typespec_probe_child {
      /// Zero-sized marker type implementing `Store`. Distinct from `State`.
      pub struct TypespecProbeChild;

      impl super::super::super::musubi::Store for TypespecProbeChild {
      const MODULE: &'static str = "Musubi.TestSupport.TypespecProbeChild";
      type State = State;
      type Params = Params;
      }

      /// The store's rendered shape: state fields plus one `UploadSlot` per
      /// declared upload. Reached as `<TypespecProbeChild as Store>::State`.
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct State {
      pub amount: i64,
      }

      #{@ext_doc}pub trait TypespecProbeChildExt {
      fn amount(&self) -> super::super::super::musubi::State<i64>;
      }

      impl TypespecProbeChildExt for super::super::super::musubi::State<State> {
      fn amount(&self) -> super::super::super::musubi::State<i64> {
      self.child("amount")
      }
      }

      impl TypespecProbeChildExt for super::super::super::musubi::StoreState<State> {
      fn amount(&self) -> super::super::super::musubi::State<i64> {
      TypespecProbeChildExt::amount(&self.fields())
      }
      }

      /// The mount params object, one field per `attr/3` declaration: required
      /// attrs are plain fields, optional ones `Option` that serialize to an
      /// absent key rather than an explicit `null`. A store declaring no `attr`
      /// gets an empty struct, which serializes to `{}`.
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct Params {}
      }
      }
      }

      // Navigation traits, flat. One `use <bundle>::nav::*;` per consumer file
      // brings every generated accessor into scope.
      pub mod nav {
      pub use super::musubi::test_support::typespec_probe_child::TypespecProbeChildExt;
      }
      """

      rendered = Rust.render([entry(TypespecProbeChild)])

      assert normalize(rendered) == normalize(@merged_preamble <> "\n" <> expected)
    end

    test "streams, async values and child stores project onto the runtime types" do
      rendered = Rust.render([entry(TypespecProbe), entry(TypespecProbeChild)])
      prelude = "super::super::super::musubi"
      child = "super::super::super::musubi::test_support::typespec_probe_child::State"

      assert rendered =~ "pub messages: Vec<String>,"

      assert normalize(rendered) =~
               normalize("""
               pub items:
                   Vec<#{child}>,
               """)

      assert rendered =~ "pub tags: Vec<String>,"

      # Past 100 columns the generic argument list is wrapped exactly the way
      # rustfmt wraps it, so the bundle survives `cargo fmt --all --check`.
      assert normalize(rendered) =~
               normalize("""
               pub load_stream: #{prelude}::AsyncResult<
                   Vec<#{child}>,
               >,
               """)

      assert normalize(rendered) =~
               normalize("""
               pub profile: #{prelude}::AsyncResult<
                   #{child},
               >,
               """)

      assert normalize(rendered) =~
               normalize("""
               pub child: #{prelude}::StoreField<
                   #{child},
               >,
               """)
    end

    test "no emitted field line exceeds rustfmt's 100-column max_width" do
      rendered = Rust.render(Enum.map(all_probes(), &entry/1))

      over_width =
        rendered
        |> String.split("\n")
        |> Enum.filter(&(String.contains?(&1, "pub ") and String.length(&1) > 100))

      assert over_width == []
    end

    # The stronger form of the assertion above: §4.1 makes the bundle
    # rustfmt-stable by construction, so a consumer running `cargo fmt --check`
    # over it must see no diff. Skipped where rustfmt is not installed — CI's
    # `cargo fmt --all --check` job covers the crates, this covers the bundle.
    test "the rendered bundle survives `rustfmt --check` unchanged" do
      rustfmt = System.find_executable("rustfmt")

      path =
        Path.join(
          System.tmp_dir!(),
          "musubi_rust_bundle_#{System.unique_integer([:positive])}.rs"
        )

      if rustfmt do
        on_exit(fn -> File.rm(path) end)
        File.write!(path, Rust.render(Enum.map(all_probes(), &entry/1)))

        assert {_output, 0} =
                 System.cmd(rustfmt, ["--edition", "2024", "--check", path],
                   stderr_to_stdout: true
                 )
      end
    end

    test "`Module.t()` on a store points at its `State`, never at the marker" do
      rendered = Rust.render([entry(TypespecProbe), entry(TypespecProbeChild)])

      refute rendered =~ "musubi::test_support::TypespecProbeChild"
    end

    test "a union of maps sharing a distinct-atom key hoists an internally tagged enum" do
      rendered = Rust.render([entry(TypespecProbe)])

      assert rendered =~ "pub status: TypespecProbeStatus,"

      assert normalize(rendered) =~
               normalize("""
               #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
               #[serde(tag = "type")]
               pub enum TypespecProbeStatus {
                   #[serde(rename = "active")]
                   Active,
                   #[serde(rename = "paused")]
                   Paused { value: i64 },
               }
               """)
    end
  end

  # The navigation column of `docs/rust-reactive-state.md` §4.3: the snapshot
  # struct is unchanged, and every field also gets an accessor whose return
  # type is fixed by the field's manifest type.
  describe "render/1 — navigation surface" do
    setup do
      {:ok, rendered: normalize(Rust.render([entry(TypespecProbe), entry(TypespecProbeChild)]))}
    end

    test "a stream is keyed, a list is indexed", %{rendered: rendered} do
      child = "super::super::super::musubi::test_support::typespec_probe_child::State"

      assert rendered =~ "fn messages(&self) -> super::super::super::musubi::StreamState<String>;"
      assert rendered =~ "fn tags(&self) -> super::super::super::musubi::State<Vec<String>>;"

      assert rendered =~
               normalize("""
               fn items(
                   &self,
               ) -> super::super::super::musubi::StreamState<
                   #{child},
               >;
               """)
    end

    test "a child store navigates as StoreState, an async node as AsyncState", %{
      rendered: rendered
    } do
      child = "super::super::super::musubi::test_support::typespec_probe_child::State"

      assert rendered =~
               normalize("""
               fn child(
                   &self,
               ) -> super::super::super::musubi::StoreState<
                   #{child},
               >;
               """)

      assert rendered =~
               normalize("""
               fn profile(
                   &self,
               ) -> super::super::super::musubi::AsyncState<
                   #{child},
               >;
               """)

      # `stream_async`: the result is a stream, so the handle is
      # `AsyncState<Vec<T>>` — the shape `ok_stream()` is defined on.
      assert rendered =~
               normalize("""
               fn load_stream(
                   &self,
               ) -> super::super::super::musubi::AsyncState<
                   Vec<#{child}>,
               >;
               """)
    end

    test "a union is a leaf: the hoisted enum navigates as State<E>, with no Ext", %{
      rendered: rendered
    } do
      assert rendered =~
               "fn status(&self) -> super::super::super::musubi::State<TypespecProbeStatus>;"

      refute rendered =~ "TypespecProbeStatusExt"
    end

    test "a store shape carries two impls, the second forwarding through fields()", %{
      rendered: rendered
    } do
      assert rendered =~
               normalize("""
               impl TypespecProbeChildExt for super::super::super::musubi::State<State> {
                   fn amount(&self) -> super::super::super::musubi::State<i64> {
                       self.child("amount")
                   }
               }
               """)

      assert rendered =~
               normalize("""
               impl TypespecProbeChildExt for super::super::super::musubi::StoreState<State> {
                   fn amount(&self) -> super::super::super::musubi::State<i64> {
                       TypespecProbeChildExt::amount(&self.fields())
                   }
               }
               """)
    end

    test "an upload slot navigates to UploadSlotState" do
      rendered = normalize(Rust.render([entry(TypespecProbeWithUpload)]))

      assert rendered =~ "fn avatar(&self) -> super::super::super::musubi::UploadSlotState;"

      assert rendered =~
               normalize("""
               fn cover(&self) -> super::super::super::musubi::UploadSlotState {
                   self.child("cover").into()
               }
               """)
    end

    test "an accessor addresses the wire key, not the escaped ident" do
      rendered = normalize(Rust.render([entry(TypespecProbeNestedState)]))

      assert rendered =~
               normalize("""
               fn r#type(&self) -> super::super::musubi::State<TypespecProbeNestedStateType> {
                   self.child("type")
               }
               """)
    end

    test "shapes that never reach the state tree get no navigation" do
      rendered = Rust.render([entry(TypespecProbeWithAttrs), entry(TypespecProbeWithReply)])

      # A struct hoisted out of an `attr` (mount params) and a command reply
      # are not nodes of any tree.
      assert rendered =~ "pub struct TypespecProbeWithAttrsParamsFilter {"
      refute rendered =~ "TypespecProbeWithAttrsParamsFilterExt"
      refute rendered =~ "PayReplyExt"
      refute rendered =~ "ParamsExt"
    end

    test "the nav module is the last top-level item and lists every trait" do
      rendered = Rust.render(Enum.map(all_probes(), &entry/1))

      traits = captures(~r/pub trait (\w+) \{/, rendered)
      exported = captures(~r/pub use super::[\w:]*?(\w+);/, rendered)

      assert Enum.sort(traits) == Enum.sort(exported)

      [_bundle, tail] = String.split(rendered, "pub mod nav {\n")
      lines = String.split(tail, "\n", trim: true)

      assert Enum.all?(lines, &(String.starts_with?(&1, "    pub use super::") or &1 == "}"))
    end

    test "a top-level module colliding with the nav module raises" do
      assert_raise ArgumentError, ~r/navigation re-export module/, fn ->
        Rust.render([{Nav.CartStore, store_entry()}])
      end
    end

    test "a prelude configured as `nav` raises" do
      assert_raise ArgumentError, ~r/navigation re-export module/, fn ->
        Rust.render([], root_module: "nav")
      end
    end
  end

  describe "render/1 — commands" do
    test "an empty payload is a braced struct and an empty reply is musubi::NoReply" do
      rendered = Rust.render([entry(TypespecProbeWithCommand)])
      prelude = "super::super::super::musubi"

      assert rendered =~ "pub struct Refresh {}"

      assert normalize(rendered) =~
               normalize("""
               impl #{prelude}::Command<TypespecProbeWithCommand> for Refresh {
                   const NAME: &'static str = "refresh";
                   type Reply = #{prelude}::NoReply;
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               pub struct Select {
                   pub id: String,
               }
               """)
    end

    test "a declared reply emits its own struct wired through type Reply" do
      rendered = Rust.render([entry(TypespecProbeWithReply)])
      prelude = "super::super::super::musubi"

      assert normalize(rendered) =~
               normalize("""
               pub struct PayReply {
                   pub ok: bool,
                   /// failure detail
                   pub message: Option<String>,
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               impl #{prelude}::Command<TypespecProbeWithReply> for Pay {
                   const NAME: &'static str = "pay";
                   type Reply = PayReply;
               }
               """)
    end
  end

  describe "render/1 — push events" do
    test "each event emits a <Name>Payload struct implementing Event" do
      rendered = Rust.render([entry(TypespecProbeWithEvents)])
      prelude = "super::super::super::musubi"

      assert rendered =~ "pub struct PingPayload {}"

      assert normalize(rendered) =~
               normalize("""
               /// Push event payload (BDR-0032).
               #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
               pub struct ToastPayload {
                   pub msg: String,
                   pub level: String,
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               impl #{prelude}::Event<TypespecProbeWithEvents> for ToastPayload {
                   const NAME: &'static str = "toast";
               }
               """)
    end
  end

  describe "render/1 — uploads" do
    test "declared uploads append inert UploadSlot fields to the store shape" do
      rendered = Rust.render([entry(TypespecProbeWithUpload)])
      prelude = "super::super::super::musubi"

      assert normalize(rendered) =~
               normalize("""
               pub struct State {
                   pub avatar_url: Option<String>,
                   pub avatar: #{prelude}::UploadSlot,
                   pub cover: #{prelude}::UploadSlot,
               }
               """)
    end

    test "an upload name colliding with a state field raises at generation time" do
      bad_entry =
        {TypespecProbeWithUpload,
         %{
           kind: :store,
           fields: [%{name: :avatar, type: quote(do: String.t()), opts: []}],
           commands: [],
           events: [],
           uploads: [%Musubi.Upload.Config{name: :avatar, accept: [".png"]}]
         }}

      assert_raise ArgumentError, ~r/collides with a state field/, fn ->
        Rust.render([bad_entry])
      end
    end
  end

  describe "render/1 — mount params" do
    test "attrs become a Params struct, required plain and optional a skipped Option" do
      rendered = Rust.render([entry(TypespecProbeWithAttrs), entry(TypespecProbeChild)])
      child = "super::super::super::musubi::test_support::typespec_probe_child::State"

      assert normalize(rendered) =~
               normalize("""
               pub struct Params {
                   pub room_id: String,
                   pub child: #{child},
                   #[serde(skip_serializing_if = "Option::is_none")]
                   pub locale: Option<String>,
                   #[serde(skip_serializing_if = "Option::is_none")]
                   pub since: Option<i64>,
                   #[serde(skip_serializing_if = "Option::is_none")]
                   pub filter: Option<TypespecProbeWithAttrsParamsFilter>,
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               pub struct TypespecProbeWithAttrsParamsFilter {
                   pub tag: String,
               }
               """)
    end
  end

  describe "render/1 — bundle invariants" do
    setup do
      {:ok, rendered: Rust.render(Enum.map(all_probes(), &entry/1))}
    end

    test "input order doesn't affect output", %{rendered: rendered} do
      reversed = all_probes() |> Enum.reverse() |> Enum.map(&entry/1) |> Rust.render()

      assert reversed == rendered
    end

    test "duplicate entries for one module render once", %{rendered: rendered} do
      duplicated = Rust.render(Enum.map(all_probes() ++ all_probes(), &entry/1))

      assert duplicated == rendered
    end

    test "the only `use`s are the prelude re-export and the nav module", %{rendered: rendered} do
      lines = String.split(rendered, "\n")
      uses = Enum.filter(lines, &(&1 =~ "pub use "))

      refute Enum.any?(lines, &String.starts_with?(&1, "use "))
      refute Enum.any?(lines, &String.starts_with?(&1, "pub use "))
      assert Enum.count(uses, &(&1 =~ "::generated::{")) == 1
      assert Enum.all?(uses -- [hd(uses)], &(&1 =~ ~r/pub use super::.*Ext;$/))
    end

    test "no crate-absolute paths — cross-module refs are super:: chains", %{rendered: rendered} do
      refute rendered =~ "crate::"
      assert rendered =~ "super::super::super::musubi::"
    end

    test "no container renames, no strict structs, no TS-only markers", %{rendered: rendered} do
      refute rendered =~ "rename_all"
      refute rendered =~ "deny_unknown_fields"
      refute rendered =~ "serde(default)"
      refute rendered =~ "StreamField"
      refute rendered =~ "STORES"
      refute rendered =~ "__musubi_store_id__"
    end

    test "every atom-literal variant carries an explicit rename", %{rendered: rendered} do
      normalized = normalize(rendered)

      assert normalized =~ ~s|#[serde(rename = "guest")]\nGuest,|
      assert normalized =~ ~s|#[serde(rename = "member")]\nMember,|
      assert normalized =~ ~s|#[serde(rename = "paused")]\nPaused { value: i64 },|
    end
  end

  describe "render/2 — options" do
    test ":root_module retargets the prelude module and every path into it" do
      rendered = Rust.render([entry(TypespecProbeChild)], root_module: "rt")

      assert rendered =~ "pub mod rt {"
      assert rendered =~ "impl super::super::super::rt::Store for TypespecProbeChild {"
      refute rendered =~ "pub mod musubi {\n    pub use"
    end

    test ":runtime_path retargets the crate owning the shared types" do
      rendered = Rust.render([], runtime_path: "my_crate::musubi")

      assert rendered =~ "pub use ::my_crate::musubi::generated::{"
      refute rendered =~ "::musubi_client::"
    end
  end

  describe "render/1 — module path collisions" do
    test "two modules underscoring to the same rust path raise" do
      entries = [{MyApp.FOO, empty_state()}, {MyApp.Foo, empty_state()}]

      assert_raise ArgumentError, ~r/collide.*rust module path/, fn ->
        Rust.render(entries)
      end
    end

    # The full-path check never sees this pair: one segment is intermediate,
    # the other is an entry module, so only the emitted `pub mod` tree collides.
    test "an intermediate segment colliding with another module's own segment raises" do
      entries = [{MyApp.Foo.Bar, empty_state()}, {MyApp.FOO, store_entry()}]

      assert_raise ArgumentError, ~r/collide.*rust module path/, fn ->
        Rust.render(entries)
      end
    end

    test "an Elixir segment underscoring to a rust keyword is emitted as a raw identifier" do
      rendered = Rust.render([{MyApp.Match.CartStore, store_entry()}])

      assert rendered =~ "pub mod r#match {"
      assert rendered =~ "pub mod cart_store {"
    end

    test "a segment underscoring to a keyword that cannot be raw raises" do
      assert_raise ArgumentError, ~r/reserved Rust module name/, fn ->
        Rust.render([{MyApp.Crate.CartStore, store_entry()}])
      end
    end
  end

  defp all_probes do
    [
      TypespecProbe,
      TypespecProbeChild,
      TypespecProbeNestedState,
      TypespecProbeWithAttrs,
      TypespecProbeWithCommand,
      TypespecProbeWithEvents,
      TypespecProbeWithReply,
      TypespecProbeWithUpload
    ]
  end

  defp entry(module) do
    data = Manifest.collect(module.__env__())
    {data.module, Map.take(data, [:kind, :fields, :commands, :events, :attrs, :uploads])}
  end

  defp empty_state,
    do: %{kind: :state, fields: [], commands: [], events: [], attrs: [], uploads: []}

  defp store_entry, do: %{empty_state() | kind: :store}

  defp state_entry(field_name, type_ast),
    do: %{empty_state() | fields: [%{name: field_name, type: type_ast, opts: []}]}

  defp captures(regex, source) do
    regex
    |> Regex.scan(source, capture: :all_but_first)
    |> List.flatten()
  end

  # Strip leading whitespace from every line so assertions exercise the line
  # CONTENT (and ordering) without coupling to nesting depth.
  defp normalize(source) do
    source
    |> String.split("\n")
    |> Enum.map_join("\n", &String.trim_leading/1)
  end
end
