defmodule Musubi.Codegen.RustTest do
  use ExUnit.Case, async: true

  alias Musubi.Codegen.Manifest
  alias Musubi.Codegen.Rust
  alias Musubi.TestSupport.TypespecProbe
  alias Musubi.TestSupport.TypespecProbeChild
  alias Musubi.TestSupport.TypespecProbeNestedState
  alias Musubi.TestSupport.TypespecProbeWithAttrs
  alias Musubi.TestSupport.TypespecProbeWithCommand
  alias Musubi.TestSupport.TypespecProbeWithEvents
  alias Musubi.TestSupport.TypespecProbeWithReply
  alias Musubi.TestSupport.TypespecProbeWithUpload

  doctest Musubi.Codegen.Rust

  @preamble """
  // Generated by `mix compile.musubi_rust`. Do not edit by hand.
  // Include as a module file (`mod generated;`) or via `include!`.

  #![allow(clippy::all, dead_code, unused_imports)]

  // Prelude: re-exports only. The shared runtime types are owned by the
  // client crate (`:rust_codegen_runtime_path`, default `musubi_client`).
  pub mod musubi {
      pub use ::musubi_client::generated::{
          AsyncError, AsyncResult, Command, Event, NoReply, Store, StoreField, StoreId, UploadSlot,
      };
  }
  """

  # The probe fixtures live under `Musubi.*`, whose top-level `pub mod musubi`
  # carries the same Rust name as the prelude module. The re-export is then the
  # first item of *that* module rather than a sibling `pub mod musubi`, which
  # would be `error[E0428]`.
  @merged_preamble """
  // Generated by `mix compile.musubi_rust`. Do not edit by hand.
  // Include as a module file (`mod generated;`) or via `include!`.

  #![allow(clippy::all, dead_code, unused_imports)]

  pub mod musubi {
      // Prelude: re-exports only. The shared runtime types are owned by the
      // client crate (`:rust_codegen_runtime_path`, default `musubi_client`).
      pub use ::musubi_client::generated::{
          AsyncError, AsyncResult, Command, Event, NoReply, Store, StoreField, StoreId, UploadSlot,
      };
  """

  describe "render/1 — empty" do
    test "renders the header and the re-export prelude only" do
      assert Rust.render([]) == @preamble
    end
  end

  describe "render/1 — Musubi.State entry" do
    test "emits a bare struct in the parent module with its hoisted types sorted by name" do
      expected = """
      pub mod test_support {
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct TypespecProbeNestedState {
      pub r#type: TypespecProbeNestedStateType,
      pub shipping: TypespecProbeNestedStateShipping,
      }

      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct TypespecProbeNestedStateShipping {
      pub street: String,
      pub city: String,
      }

      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub enum TypespecProbeNestedStateType {
      #[serde(rename = "guest")]
      Guest,
      #[serde(rename = "member")]
      Member,
      }
      }
      }
      """

      rendered = Rust.render([entry(TypespecProbeNestedState)])

      assert normalize(rendered) == normalize(@merged_preamble <> "\n" <> expected)
    end
  end

  describe "render/1 — nested state modules" do
    test "a leaf with children emits both the struct and a same-named module" do
      entries = [
        {MyApp.States.Cart, state_entry(:title, quote(do: String.t()))},
        {MyApp.States.Cart.Item, state_entry(:sku, quote(do: String.t()))}
      ]

      expected = """
      pub mod my_app {
      pub mod states {
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct Cart {
      pub title: String,
      }

      pub mod cart {
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct Item {
      pub sku: String,
      }
      }
      }
      }
      """

      assert normalize(Rust.render(entries)) == normalize(@preamble <> "\n" <> expected)
    end
  end

  describe "render/1 — Musubi.Store entry" do
    test "a store is a module of its own carrying the marker, the impl and State" do
      expected = """
      pub mod test_support {
      pub mod typespec_probe_child {
      /// Zero-sized marker type implementing `Store`. Distinct from `State`.
      pub struct TypespecProbeChild;

      impl super::super::super::musubi::Store for TypespecProbeChild {
      const MODULE: &'static str = "Musubi.TestSupport.TypespecProbeChild";
      type State = State;
      type Params = Params;
      }

      /// The store's rendered shape: state fields plus one `UploadSlot` per
      /// declared upload. Reached as `<TypespecProbeChild as Store>::State`.
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct State {
      pub amount: i64,
      }

      /// The mount params object, one field per `attr/3` declaration: required
      /// attrs are plain fields, optional ones `Option` that serialize to an
      /// absent key rather than an explicit `null`. A store declaring no `attr`
      /// gets an empty struct, which serializes to `{}`.
      #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
      pub struct Params {}
      }
      }
      }
      """

      rendered = Rust.render([entry(TypespecProbeChild)])

      assert normalize(rendered) == normalize(@merged_preamble <> "\n" <> expected)
    end

    test "streams, async values and child stores project onto the runtime types" do
      rendered = Rust.render([entry(TypespecProbe), entry(TypespecProbeChild)])
      prelude = "super::super::super::musubi"
      child = "super::super::super::musubi::test_support::typespec_probe_child::State"

      assert rendered =~ "pub messages: Vec<String>,"

      assert normalize(rendered) =~
               normalize("""
               pub items:
                   Vec<#{child}>,
               """)

      assert rendered =~ "pub tags: Vec<String>,"

      # Past 100 columns the generic argument list is wrapped exactly the way
      # rustfmt wraps it, so the bundle survives `cargo fmt --all --check`.
      assert normalize(rendered) =~
               normalize("""
               pub load_stream: #{prelude}::AsyncResult<
                   Vec<#{child}>,
               >,
               """)

      assert normalize(rendered) =~
               normalize("""
               pub profile: #{prelude}::AsyncResult<
                   #{child},
               >,
               """)

      assert normalize(rendered) =~
               normalize("""
               pub child: #{prelude}::StoreField<
                   #{child},
               >,
               """)
    end

    test "no emitted field line exceeds rustfmt's 100-column max_width" do
      rendered = Rust.render(Enum.map(all_probes(), &entry/1))

      over_width =
        rendered
        |> String.split("\n")
        |> Enum.filter(&(String.contains?(&1, "pub ") and String.length(&1) > 100))

      assert over_width == []
    end

    # The stronger form of the assertion above: §4.1 makes the bundle
    # rustfmt-stable by construction, so a consumer running `cargo fmt --check`
    # over it must see no diff. Skipped where rustfmt is not installed — CI's
    # `cargo fmt --all --check` job covers the crates, this covers the bundle.
    test "the rendered bundle survives `rustfmt --check` unchanged" do
      rustfmt = System.find_executable("rustfmt")

      path =
        Path.join(
          System.tmp_dir!(),
          "musubi_rust_bundle_#{System.unique_integer([:positive])}.rs"
        )

      if rustfmt do
        on_exit(fn -> File.rm(path) end)
        File.write!(path, Rust.render(Enum.map(all_probes(), &entry/1)))

        assert {_output, 0} =
                 System.cmd(rustfmt, ["--edition", "2024", "--check", path],
                   stderr_to_stdout: true
                 )
      end
    end

    test "`Module.t()` on a store points at its `State`, never at the marker" do
      rendered = Rust.render([entry(TypespecProbe), entry(TypespecProbeChild)])

      refute rendered =~ "musubi::test_support::TypespecProbeChild"
    end

    test "a union of maps sharing a distinct-atom key hoists an internally tagged enum" do
      rendered = Rust.render([entry(TypespecProbe)])

      assert rendered =~ "pub status: TypespecProbeStatus,"

      assert normalize(rendered) =~
               normalize("""
               #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
               #[serde(tag = "type")]
               pub enum TypespecProbeStatus {
                   #[serde(rename = "active")]
                   Active,
                   #[serde(rename = "paused")]
                   Paused { value: i64 },
               }
               """)
    end
  end

  describe "render/1 — commands" do
    test "an empty payload is a braced struct and an empty reply is musubi::NoReply" do
      rendered = Rust.render([entry(TypespecProbeWithCommand)])
      prelude = "super::super::super::musubi"

      assert rendered =~ "pub struct Refresh {}"

      assert normalize(rendered) =~
               normalize("""
               impl #{prelude}::Command<TypespecProbeWithCommand> for Refresh {
                   const NAME: &'static str = "refresh";
                   type Reply = #{prelude}::NoReply;
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               pub struct Select {
                   pub id: String,
               }
               """)
    end

    test "a declared reply emits its own struct wired through type Reply" do
      rendered = Rust.render([entry(TypespecProbeWithReply)])
      prelude = "super::super::super::musubi"

      assert normalize(rendered) =~
               normalize("""
               pub struct PayReply {
                   pub ok: bool,
                   /// failure detail
                   pub message: Option<String>,
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               impl #{prelude}::Command<TypespecProbeWithReply> for Pay {
                   const NAME: &'static str = "pay";
                   type Reply = PayReply;
               }
               """)
    end
  end

  describe "render/1 — push events" do
    test "each event emits a <Name>Payload struct implementing Event" do
      rendered = Rust.render([entry(TypespecProbeWithEvents)])
      prelude = "super::super::super::musubi"

      assert rendered =~ "pub struct PingPayload {}"

      assert normalize(rendered) =~
               normalize("""
               /// Push event payload (BDR-0032).
               #[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
               pub struct ToastPayload {
                   pub msg: String,
                   pub level: String,
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               impl #{prelude}::Event<TypespecProbeWithEvents> for ToastPayload {
                   const NAME: &'static str = "toast";
               }
               """)
    end
  end

  describe "render/1 — uploads" do
    test "declared uploads append inert UploadSlot fields to the store shape" do
      rendered = Rust.render([entry(TypespecProbeWithUpload)])
      prelude = "super::super::super::musubi"

      assert normalize(rendered) =~
               normalize("""
               pub struct State {
                   pub avatar_url: Option<String>,
                   pub avatar: #{prelude}::UploadSlot,
                   pub cover: #{prelude}::UploadSlot,
               }
               """)
    end

    test "an upload name colliding with a state field raises at generation time" do
      bad_entry =
        {TypespecProbeWithUpload,
         %{
           kind: :store,
           fields: [%{name: :avatar, type: quote(do: String.t()), opts: []}],
           commands: [],
           events: [],
           uploads: [%Musubi.Upload.Config{name: :avatar, accept: [".png"]}]
         }}

      assert_raise ArgumentError, ~r/collides with a state field/, fn ->
        Rust.render([bad_entry])
      end
    end
  end

  describe "render/1 — mount params" do
    test "attrs become a Params struct, required plain and optional a skipped Option" do
      rendered = Rust.render([entry(TypespecProbeWithAttrs), entry(TypespecProbeChild)])
      child = "super::super::super::musubi::test_support::typespec_probe_child::State"

      assert normalize(rendered) =~
               normalize("""
               pub struct Params {
                   pub room_id: String,
                   pub child: #{child},
                   #[serde(skip_serializing_if = "Option::is_none")]
                   pub locale: Option<String>,
                   #[serde(skip_serializing_if = "Option::is_none")]
                   pub since: Option<i64>,
                   #[serde(skip_serializing_if = "Option::is_none")]
                   pub filter: Option<TypespecProbeWithAttrsParamsFilter>,
               }
               """)

      assert normalize(rendered) =~
               normalize("""
               pub struct TypespecProbeWithAttrsParamsFilter {
                   pub tag: String,
               }
               """)
    end
  end

  describe "render/1 — bundle invariants" do
    setup do
      {:ok, rendered: Rust.render(Enum.map(all_probes(), &entry/1))}
    end

    test "input order doesn't affect output", %{rendered: rendered} do
      reversed = all_probes() |> Enum.reverse() |> Enum.map(&entry/1) |> Rust.render()

      assert reversed == rendered
    end

    test "duplicate entries for one module render once", %{rendered: rendered} do
      duplicated = Rust.render(Enum.map(all_probes() ++ all_probes(), &entry/1))

      assert duplicated == rendered
    end

    test "the only `use` is the prelude re-export", %{rendered: rendered} do
      lines = String.split(rendered, "\n")

      refute Enum.any?(lines, &String.starts_with?(&1, "use "))
      refute Enum.any?(lines, &String.starts_with?(&1, "pub use "))
      assert Enum.count(lines, &(&1 =~ "pub use ")) == 1
    end

    test "no crate-absolute paths — cross-module refs are super:: chains", %{rendered: rendered} do
      refute rendered =~ "crate::"
      assert rendered =~ "super::super::super::musubi::"
    end

    test "no container renames, no strict structs, no TS-only markers", %{rendered: rendered} do
      refute rendered =~ "rename_all"
      refute rendered =~ "deny_unknown_fields"
      refute rendered =~ "serde(default)"
      refute rendered =~ "StreamField"
      refute rendered =~ "STORES"
      refute rendered =~ "__musubi_store_id__"
    end

    test "every atom-literal variant carries an explicit rename", %{rendered: rendered} do
      normalized = normalize(rendered)

      assert normalized =~ ~s|#[serde(rename = "guest")]\nGuest,|
      assert normalized =~ ~s|#[serde(rename = "member")]\nMember,|
      assert normalized =~ ~s|#[serde(rename = "paused")]\nPaused { value: i64 },|
    end
  end

  describe "render/2 — options" do
    test ":root_module retargets the prelude module and every path into it" do
      rendered = Rust.render([entry(TypespecProbeChild)], root_module: "rt")

      assert rendered =~ "pub mod rt {"
      assert rendered =~ "impl super::super::super::rt::Store for TypespecProbeChild {"
      refute rendered =~ "pub mod musubi {\n    pub use"
    end

    test ":runtime_path retargets the crate owning the shared types" do
      rendered = Rust.render([], runtime_path: "my_crate::musubi")

      assert rendered =~ "pub use ::my_crate::musubi::generated::{"
      refute rendered =~ "::musubi_client::"
    end
  end

  describe "render/1 — module path collisions" do
    test "two modules underscoring to the same rust path raise" do
      entries = [{MyApp.FOO, empty_state()}, {MyApp.Foo, empty_state()}]

      assert_raise ArgumentError, ~r/collide.*rust module path/, fn ->
        Rust.render(entries)
      end
    end

    # The full-path check never sees this pair: one segment is intermediate,
    # the other is an entry module, so only the emitted `pub mod` tree collides.
    test "an intermediate segment colliding with another module's own segment raises" do
      entries = [{MyApp.Foo.Bar, empty_state()}, {MyApp.FOO, store_entry()}]

      assert_raise ArgumentError, ~r/collide.*rust module path/, fn ->
        Rust.render(entries)
      end
    end

    test "an Elixir segment underscoring to a rust keyword is emitted as a raw identifier" do
      rendered = Rust.render([{MyApp.Match.CartStore, store_entry()}])

      assert rendered =~ "pub mod r#match {"
      assert rendered =~ "pub mod cart_store {"
    end

    test "a segment underscoring to a keyword that cannot be raw raises" do
      assert_raise ArgumentError, ~r/reserved Rust module name/, fn ->
        Rust.render([{MyApp.Crate.CartStore, store_entry()}])
      end
    end
  end

  defp all_probes do
    [
      TypespecProbe,
      TypespecProbeChild,
      TypespecProbeNestedState,
      TypespecProbeWithAttrs,
      TypespecProbeWithCommand,
      TypespecProbeWithEvents,
      TypespecProbeWithReply,
      TypespecProbeWithUpload
    ]
  end

  defp entry(module) do
    data = Manifest.collect(module.__env__())
    {data.module, Map.take(data, [:kind, :fields, :commands, :events, :attrs, :uploads])}
  end

  defp empty_state,
    do: %{kind: :state, fields: [], commands: [], events: [], attrs: [], uploads: []}

  defp store_entry, do: %{empty_state() | kind: :store}

  defp state_entry(field_name, type_ast),
    do: %{empty_state() | fields: [%{name: field_name, type: type_ast, opts: []}]}

  # Strip leading whitespace from every line so assertions exercise the line
  # CONTENT (and ordering) without coupling to nesting depth.
  defp normalize(source) do
    source
    |> String.split("\n")
    |> Enum.map_join("\n", &String.trim_leading/1)
  end
end
