defmodule Musubi.Codegen.TypeScriptTest do
  use ExUnit.Case, async: true

  alias Musubi.Codegen.Manifest
  alias Musubi.Codegen.TypeScript
  alias Musubi.TestSupport.TypespecProbe
  alias Musubi.TestSupport.TypespecProbeChild
  alias Musubi.TestSupport.TypespecProbeWithCommand

  defp entry(module) do
    data = Manifest.collect(module.__env__())
    {data.module, Map.take(data, [:kind, :fields, :commands, :events, :uploads])}
  end

  # Strip leading whitespace from every line so assertions exercise the line
  # CONTENT (and ordering) without coupling to indentation depth.
  defp normalize(s) do
    s
    |> String.split("\n")
    |> Enum.map_join("\n", &String.trim_leading/1)
  end

  @preamble """
  // Generated by `mix compile.musubi_ts`. Do not edit by hand.

  declare namespace Musubi {
    type StoreId = string[]

    type AsyncError =
      | { kind: "error"; value: unknown }
      | { kind: "exit"; value: unknown }

    type AsyncResult<T> =
      | { __musubi_async__: true; status: "loading"; result: T | null; reason: null }
      | { __musubi_async__: true; status: "ok"; result: T; reason: null }
      | { __musubi_async__: true; status: "failed"; result: T | null; reason: AsyncError | unknown }

    const Type: unique symbol

    interface StoreDef<Module extends string, Shape, Commands, Events = {}> {
      readonly [Type]: {
        module: Module
        shape: Shape
        commands: Commands
        events: Events
      }
    }

    type StoreField<Module extends string> = {
      readonly [Type]: { kind: "store"; module: Module }
    }

    type StreamField<Item> = {
      readonly [Type]: { kind: "stream"; item: Item }
    }

    type AsyncField<Value> = {
      readonly [Type]: { kind: "async"; value: Value }
    }

    type UploadConfig = {
      readonly accept: readonly string[] | "any"
      readonly maxEntries: number
      readonly maxFileSize: number
      readonly chunkSize: number
    }

    type UploadEntryStatus =
      | "pending"
      | "uploading"
      | "success"
      | "error"
      | "cancelled"

    type UploadStatus =
      | "idle"
      | "selecting"
      | "uploading"
      | "success"
      | "error"
      | "cancelled"

    type UploadError = { readonly code: string; readonly message: string }

    type UploadEntry = {
      readonly ref: string
      readonly clientName: string
      readonly clientSize: number
      readonly clientType: string
      readonly progress: number
      readonly status: UploadEntryStatus
      readonly errors: readonly UploadError[]
    }

    type UploadHandle = {
      readonly config: UploadConfig
      readonly status: UploadStatus
      readonly entries: readonly UploadEntry[]
      readonly errors: readonly UploadError[]
      readonly progress: number
      readonly isIdle: boolean
      readonly isSelecting: boolean
      readonly isUploading: boolean
      readonly isSuccess: boolean
      readonly isError: boolean
      select(files: FileList | File[]): Promise<readonly UploadEntry[]>
      start(): Promise<void>
      cancel(entryRef?: string): Promise<void>
      reset(): Promise<void>
    }

    type UploadField = {
      readonly [Type]: { kind: "upload" }
    }

  """

  describe "render/1 — empty" do
    test "renders just the preamble with an empty Stores interface" do
      expected =
        @preamble <>
          """
            interface Stores {}
          }
          """

      assert normalize(TypeScript.render([])) == normalize(expected)
    end
  end

  describe "render/1 — Musubi.Store entry" do
    test "store without commands populates Musubi.Stores with an empty commands map" do
      expected =
        @preamble <>
          """
            interface Stores {
              "Musubi.TestSupport.TypespecProbeChild": StoreDef<
                "Musubi.TestSupport.TypespecProbeChild",
                {
                  amount: number
                },
                {},
                {}
              >
            }
          }
          """

      assert normalize(TypeScript.render([entry(TypespecProbeChild)])) == normalize(expected)
    end

    test "store with commands emits payload + reply schema per command" do
      expected =
        @preamble <>
          """
            interface Stores {
              "Musubi.TestSupport.TypespecProbeWithCommand": StoreDef<
                "Musubi.TestSupport.TypespecProbeWithCommand",
                {
                  selected_id: string | null
                },
                {
                  select: {
                    payload: {
                      id: string
                    }
                    reply: never
                  }
                  refresh: {
                    payload: {}
                    reply: never
                  }
                },
                {}
              >
            }
          }
          """

      assert normalize(TypeScript.render([entry(TypespecProbeWithCommand)])) ==
               normalize(expected)
    end

    test "root store with events emits the event payload schema in the 4th slot" do
      expected =
        @preamble <>
          """
            interface Stores {
              "Musubi.TestSupport.TypespecProbeWithEvents": StoreDef<
                "Musubi.TestSupport.TypespecProbeWithEvents",
                {
                  title: string
                },
                {},
                {
                  ping: {
                    payload: {}
                  }
                  toast: {
                    payload: {
                      msg: string
                      level: string
                    }
                  }
                }
              >
            }
          }
          """

      assert normalize(TypeScript.render([entry(Musubi.TestSupport.TypespecProbeWithEvents)])) ==
               normalize(expected)
    end
  end

  describe "render/1 — multiple modules" do
    test "stores share Musubi.Stores; phantom markers project special fields" do
      rendered = TypeScript.render([entry(TypespecProbe), entry(TypespecProbeChild)])

      # Both stores appear in Musubi.Stores
      assert rendered =~ ~s["Musubi.TestSupport.TypespecProbe": StoreDef<]
      assert rendered =~ ~s["Musubi.TestSupport.TypespecProbeChild": StoreDef<]

      # stream(T) -> StreamField, nested store ref -> StoreField,
      # AsyncResult.of(stream(T)) -> AsyncField<StreamField<T>>
      assert rendered =~ "messages: Musubi.StreamField<string>"
      assert rendered =~ "items: Musubi.StreamField<Musubi.TestSupport.TypespecProbeChild>"

      assert rendered =~
               "load_stream: Musubi.AsyncField<Musubi.StreamField<Musubi.TestSupport.TypespecProbeChild>>"

      assert rendered =~
               "profile: Musubi.AsyncField<Musubi.TestSupport.TypespecProbeChild>"

      assert rendered =~
               ~s|child: Musubi.StoreField<"Musubi.TestSupport.TypespecProbeChild">|

      assert rendered =~ "tags: string[]"

      # Generated stores never embed __musubi_store_id__ in the declared shape;
      # the runtime member is added by the client proxy.
      refute rendered =~ "__musubi_store_id__"

      # Old "declare module \"@musubi/client\"" augmentation is gone.
      refute rendered =~ ~s|declare module "@musubi/client"|

      # Bundle is ambient (no top-level `declare global` / no `export {}`).
      refute rendered =~ "declare global"
      refute rendered =~ "export {}"
    end

    test "input order doesn't affect output (sorted alphabetically by Module.split)" do
      forward = TypeScript.render([entry(TypespecProbe), entry(TypespecProbeChild)])
      reversed = TypeScript.render([entry(TypespecProbeChild), entry(TypespecProbe)])
      assert forward == reversed
    end
  end

  describe "render/1 — ambient .d.ts bundle" do
    test "no `declare global` wrapper; top-level `declare namespace` is auto-loaded" do
      rendered = TypeScript.render([entry(TypespecProbeChild)])

      assert String.starts_with?(
               rendered,
               "// Generated by `mix compile.musubi_ts`. Do not edit by hand.\n"
             )

      refute rendered =~ "declare global"
      refute rendered =~ "export {}"
      assert rendered =~ "declare namespace Musubi"
    end

    test "respects the :root_namespace option for the entire bundle" do
      rendered = TypeScript.render([entry(TypespecProbeChild)], root_namespace: "MyApp")

      assert rendered =~ "declare namespace MyApp {"
      refute rendered =~ "declare namespace Musubi"
    end
  end

  describe "render/1 — upload handles" do
    alias Musubi.TestSupport.TypespecProbeWithUpload

    test "declared uploads emit UploadField fields merged into the store shape" do
      rendered = TypeScript.render([entry(TypespecProbeWithUpload)])

      assert rendered =~ "avatar_url: string | null"
      assert rendered =~ "avatar: UploadField"
      assert rendered =~ "cover: UploadField"
    end

    test "preamble declares UploadHandle / UploadField shared types" do
      rendered = TypeScript.render([entry(TypespecProbeWithUpload)])

      assert rendered =~ "type UploadHandle = {"
      assert rendered =~ "type UploadField = {"
      assert rendered =~ "kind: \"upload\""
    end

    test "upload name colliding with a state field raises at generation time" do
      bad_entry =
        {Musubi.TestSupport.TypespecProbeWithUpload,
         %{
           kind: :store,
           fields: [%{name: :avatar, type: quote(do: String.t())}],
           commands: [],
           uploads: [%Musubi.Upload.Config{name: :avatar, accept: [".png"]}]
         }}

      assert_raise ArgumentError, ~r/collides with a state field/, fn ->
        TypeScript.render([bad_entry])
      end
    end
  end
end
