name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Hex
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup environment
        uses: ./.github/workflows/actions/setup

      - name: Compile with warnings as errors
        run: mix compile --warnings-as-errors

      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
